<?php

namespace App\Livewire\Masters;

use App\Models\Crop;
use App\Models\Product;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;
use Livewire\WithFileUploads;
use Illuminate\Support\Facades\Storage;

class CropForm extends Component
{
    use WithFileUploads;

    public $cropId;
    public $name;
    public $image;
    public $existingImage;
    public $description;
    public $isActive = true;
    public $sortOrder = 0;
    public $uniqueId; // Display only, auto-generated
    public $selectedProducts = []; // Array of product IDs
    public $availableProducts = []; // All available products

    public function mount($crop = null)
    {
        // Load available products (from user's organization)
        $user = Auth::user();
        if ($user && $user->organization_id) {
            $this->availableProducts = Product::where('organization_id', $user->organization_id)
                ->where('is_active', true)
                ->orderBy('name')
                ->get();
        } else {
            $this->availableProducts = Product::where('is_active', true)
                ->orderBy('name')
                ->get();
        }

        if ($crop) {
            if (is_object($crop)) {
                $cropModel = $crop;
            } else {
                $cropModel = Crop::with('products')->findOrFail($crop);
            }

            $this->cropId = $cropModel->id;
            $this->name = $cropModel->name;
            $this->uniqueId = $cropModel->unique_id;
            $this->existingImage = $cropModel->image;
            $this->description = $cropModel->description;
            $this->isActive = $cropModel->is_active;
            $this->sortOrder = $cropModel->sort_order;
            
            // Load existing product relationships
            $this->selectedProducts = $cropModel->products->pluck('id')->toArray();
        }
    }

    public function save()
    {
        $validated = $this->validate([
            'name' => 'required|string|max:255',
            'image' => $this->cropId ? 'nullable|image|max:2048' : 'required|image|max:2048',
            'description' => 'nullable|string',
            'isActive' => 'boolean',
            'sortOrder' => 'nullable|integer|min:0',
            'selectedProducts' => 'nullable|array',
            'selectedProducts.*' => 'exists:products,id',
        ]);

        $imagePath = $this->existingImage;

        // Handle image upload
        if ($this->image) {
            // Delete old image if exists
            if ($this->existingImage && Storage::disk('public')->exists($this->existingImage)) {
                Storage::disk('public')->delete($this->existingImage);
            }

            // Store new image
            $imagePath = $this->image->store('crops', 'public');
        }

        if ($this->cropId) {
            $crop = Crop::findOrFail($this->cropId);
            $crop->update([
                'name' => $this->name,
                'image' => $imagePath,
                'description' => $this->description,
                'is_active' => $this->isActive,
                'sort_order' => $this->sortOrder,
            ]);

            // Sync products
            $crop->products()->sync($this->selectedProducts);

            session()->flash('message', 'Crop updated successfully');
        } else {
            // unique_id will be auto-generated by the model
            $crop = Crop::create([
                'name' => $this->name,
                'image' => $imagePath,
                'description' => $this->description,
                'is_active' => $this->isActive,
                'sort_order' => $this->sortOrder,
            ]);

            // Sync products
            $crop->products()->sync($this->selectedProducts);

            session()->flash('message', 'Crop created successfully');
        }

        return redirect()->route('crops.index');
    }

    public function render()
    {
        return view('livewire.masters.crop-form');
    }
}
